port: {{ env "EKBO_PORT" "9180" }}
path:
  connect: {{ env "EKBO_CONNECT_PATH" "/connect" }}
  close: {{ env "EKBO_CLOSE_PATH" "/close" }}
  stats: {{ env "EKBO_STATS_PATH" "/stats" }}
  send: {{ env "EKBO_SEND_PATH" "/send" }}
  ping: {{ env "EKBO_PING_PATH" "/ping" }}
callback:
  connect: {{ env "EKBO_CONNECT_CALLBACK_URL" "http://localhost:12346/connect" }}
  close: {{ env "EKBO_CLOSE_CALLBACK_URL" "" }}
  receive: {{ env "EKBO_RECEIVE_CALLBACK_URL" "" }}
  timeout: {{ env "EKBO_CALLBACK_TIMEOUT" "0" }}
suppress_access_log: {{ env "EKBO_SUPPRESS_ACCESS_LOG" "false" }}
session_header: {{ env "EKBO_SESSION_HEADER_NAME" "X-Kuiperbelt-Session" }}
sock: {{ env "EKBO_UNIX_DOMAIN_SOCKET_FILENAME" "" }}
endpoint: {{ env "EKBO_SELF_ENDPOINT_URL" "" }}
strict_broadcast: {{ env "EKBO_STRICT_BROADCAST_MODE_SWITCH" "false" }}
proxy_set_header: {{ env "EKBO_PROXY_SET_HEADER" "{}" }}
send_timeout: {{ env "EKBO_SEND_TIMEOUT" "0" }}
send_queue_size: {{ env "EKBO_SEND_QUEUE_SIZE" "0" }}
origin_policy: {{ env "EKBO_ORIGIN_POLICY" "none" }}
idle_timeout: {{ env "EKBO_IDLE_TIMEOUT" "0" }}
